/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package principal;

import java.util.HashMap;
import java.util.Map;
import util.ConsumoAPI;

/**
 *
 * @author INSTRUCTOR
 */
public class Editar extends javax.swing.JPanel {

    /**
     * Creates new form Consultar
     */
    public Editar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_editar = new javax.swing.JButton();
        campo_email = new javax.swing.JTextField();
        campo_direccion = new javax.swing.JTextField();
        campo_telefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        campo_apellidos = new javax.swing.JTextField();
        campo_nombres = new javax.swing.JTextField();
        campo_cedula = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EDITAR USUARIO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 910, -1));

        btn_editar.setBackground(new java.awt.Color(0, 153, 0));
        btn_editar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_editar.setForeground(new java.awt.Color(255, 255, 255));
        btn_editar.setText("EDITAR");
        btn_editar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 150, -1));

        campo_email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(campo_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 200, -1));

        campo_direccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(campo_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 200, -1));

        campo_telefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(campo_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 200, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Telefono");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Direccion");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Email");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        campo_apellidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(campo_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 200, -1));

        campo_nombres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campo_nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nombresActionPerformed(evt);
            }
        });
        add(campo_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 200, -1));

        campo_cedula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campo_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_cedulaActionPerformed(evt);
            }
        });
        add(campo_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 200, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Cedula");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Nombres");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Apellidos");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed

        ConsumoAPI consumo = new ConsumoAPI();

        String cedula = campo_cedula.getText();
        String nombres = campo_nombres.getText();
        String apellidos = campo_apellidos.getText();
        String telefono = campo_telefono.getText();
        String direccion = campo_direccion.getText();
        String email = campo_email.getText();

        Map<String, String> datosActualizar = new HashMap<>();
        datosActualizar.put("cedula", cedula);
        datosActualizar.put("nombres", nombres);
        datosActualizar.put("apellidos", apellidos);
        datosActualizar.put("telefono", telefono);
        datosActualizar.put("direccion", direccion);
        datosActualizar.put("email", email);
        
        String respuesta03 = consumo.consumoPOST("https://codetesthub.com/API/Actualizar.php", datosActualizar);
        System.out.println("Respuesta Actualizar: " + respuesta03);
        campo_cedula.setText("");
        campo_nombres.setText("");
        campo_apellidos.setText("");
        campo_telefono.setText("");
        campo_direccion.setText("");
        campo_email.setText("");

        System.out.println("Se ha añadido con exito");
    }//GEN-LAST:event_btn_editarActionPerformed

    private void campo_nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_nombresActionPerformed

    private void campo_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_cedulaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar;
    private javax.swing.JTextField campo_apellidos;
    private javax.swing.JTextField campo_cedula;
    private javax.swing.JTextField campo_direccion;
    private javax.swing.JTextField campo_email;
    private javax.swing.JTextField campo_nombres;
    private javax.swing.JTextField campo_telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
