/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package principal;

import java.util.HashMap;
import java.util.Map;
import util.ConsumoAPI;

/**
 *
 * @author INSTRUCTOR
 */
public class Insertar extends javax.swing.JPanel {

    /**
     * Creates new form Consultar
     */
    public Insertar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        campo_email = new javax.swing.JTextField();
        campo_direccion = new javax.swing.JTextField();
        campo_telefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        campo_apellidos = new javax.swing.JTextField();
        campo_nombres = new javax.swing.JTextField();
        campo_cedula = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(880, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AGREGAR USUARIOS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 910, -1));

        btn_agregar.setBackground(new java.awt.Color(0, 153, 0));
        btn_agregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setText("AGREGAR");
        btn_agregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 150, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 450));

        campo_email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(campo_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 200, -1));

        campo_direccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(campo_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 200, -1));

        campo_telefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(campo_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 200, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Telefono");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Direccion");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Email");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        campo_apellidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(campo_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 200, -1));

        campo_nombres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campo_nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nombresActionPerformed(evt);
            }
        });
        add(campo_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 200, -1));

        campo_cedula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campo_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_cedulaActionPerformed(evt);
            }
        });
        add(campo_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 200, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Cedula");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Nombres");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Apellidos");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void campo_nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_nombresActionPerformed

    private void campo_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_cedulaActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        
        ConsumoAPI consumo = new ConsumoAPI();
        
        String cedula = campo_cedula.getText();
        String nombres = campo_nombres.getText();
        String apellidos = campo_apellidos.getText();
        String telefono = campo_telefono.getText();
        String direccion = campo_direccion.getText();
        String email = campo_email.getText();
        
        Map<String, String> datosInsertar = new HashMap<>();
        
        datosInsertar.put("cedula", cedula);
        datosInsertar.put("nombres", nombres);
        datosInsertar.put("apellidos", apellidos);
        datosInsertar.put("telefono", telefono);
        datosInsertar.put("direccion", direccion);
        datosInsertar.put("email", email);
        String respuesta02 = consumo.consumoPOST("https://codetesthub.com/API/Insertar.php", datosInsertar);
        
        campo_cedula.setText("");
        campo_nombres.setText("");
        campo_apellidos.setText("");
        campo_telefono.setText("");
        campo_direccion.setText("");
        campo_email.setText("");
        
        System.out.println("Se ha añadido con exito");
    }//GEN-LAST:event_btn_agregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JTextField campo_apellidos;
    private javax.swing.JTextField campo_cedula;
    private javax.swing.JTextField campo_direccion;
    private javax.swing.JTextField campo_email;
    private javax.swing.JTextField campo_nombres;
    private javax.swing.JTextField campo_telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
